# Driver
CONFIG_I3C=y
CONFIG_I3C_USE_IBI=y
CONFIG_I3C_IBI_WORKQUEUE=y

CONFIG_PWM=y

CONFIG_SENSOR=y

CONFIG_ADC=y

# Logging
CONFIG_LOG=y
CONFIG_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_I3C_SHELL=y
CONFIG_PWM_SHELL=y

# Compiler
# CONFIG_DEBUG_OPTIMIZATIONS=y

# Power Management
# CONFIG_PM=y
